name: Storage Manager CD
run-name: Storage Manager Continuous-Delivery
on:
  workflow_run:
    workflows: [Storage Manager CI]
    types: [completed]
    branches: [main]
env:
  DEPENDENCIES_PATH: |
    ~/.cache
    ./node_modules
  DEPENDENCIES_KEY: '**/package-lock.json'
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Ensure to trigger the deployment only with bumped versions
      - name: Getting changed files
        uses: tj-actions/changed-files@v47
        id: changed-files
        with:
          files: |
            ./package.json
            ./package-lock.json
  deploy:
    runs-on: ubuntu-latest
    needs: bump
    permissions:
      contents: read
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(needs.bump.outputs.changed-files, 'version') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Getting dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
      - name: Getting production artifacts
        uses: actions/download-artifact@v4
        with:
          name: storage-manager-production
          github-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Deploy
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
